title: Local IIIF Annotation Server
description: "Local IIIF annotation server that allows for easy annotation creation."
baseurl: "/annotate"
url: "https://blalbrit.github.io"

markdown: kramdown
permalink: pretty

theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-seo-tag

exclude: [Rakefile, Gemfile*, vendor]
include: [feed.xml]


collections:
  annotations:
    output: true
    permalink: /annotations/:name
  helpdocs:
    output: true
    permalink: /help/:name
  annotation_data:
    output: true
    permalink: /annotations/:name
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"

#api_server: https://limitless-plains-74009.herokuapp.com/annotations/
api_server: https://blalbrit.github.io/annotations/
exclude:
  - ENV/
  - imported_roles

lunr_settings:
  collections: [annotation_data]
  atozsortfield: slug
  displayfields:
    - {field: slug, headerfield: true, highlight: false}
    - {field: imagescr, headerimage: true, highlight: false}
  fields:
  - boost: 10
    jekyllfields: [content]
    searchfield: content
  - boost: 10
    jekyllfields: [tags]
    searchfield: tags
    facetfield: true

  fuzzysearchfields: [content]